name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker images
        run: |
          docker build -t task-manager:${{ github.sha }} .
  integration:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: start Docker Compose
        run: |
          docker compose up -d --build

      - name: Show container status
        run: |
          docker compose ps
      - name: wait for API
        run: |
          for i in {1..30}; do
              if curl -fsS http://localhost:8000/health; then
                echo "API is ready"
              exit 0
              fi
              sleep 2
          done
      - name: Test API
        run: |
          curl -s http://localhost:8000/health
          curl -s http://localhost:8000/api/v1/tasks
      - name: show logs
        if: always()
        run: |
          docker compose logs
      - name: stop Docker Compose
        if: always()
        run: |
          docker compose down -v

  publish:
    runs-on: ubuntu-latest
    needs: integration

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set image name
        id: image
        run: |
          OWNER="${{ github.repository_owner }}"
          OWNER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          echo "owner=$OWNER" >> "$GITHUB_OUTPUT"
          echo "Image owner: $OWNER"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.image.outputs.owner }}/task-manager:${{ github.sha }}
            ghcr.io/${{ steps.image.outputs.owner }}/task-manager:latest
